### ISSUE TITLE
Can't close modally presented ViewController any more

### ISSUE THREAD

**Issue by apm-lucas-zacharias** [SvenTiigi/STLocationRequest#10]
Until now I have used STLocationRequest in a "normal" ViewController. 
The only thing I changed was presenting the VC modally but now I can't close the VC itself anymore after showing the LocationRequest.

I use 
`self.navigationController?.dismissViewControllerAnimated(true, completion: nil)`
for closing and it's working everywhere fine but not in the VC with the LocationRequest...

**Comment by SvenTiigi** [comment]
Hey LucasZL,

there is no need to dismiss the STLocationRequestController manually. The STLocationRequestController will dismiss itself when the user tapped the NotNow-Button or accepted or denied the location request.

So please give me a code sample how you call the STLocationRequest Screen.

Preferred way in Swift, is to use the UIViewController Extension:

``` swift
import STLocationRequest

func showLocationRequest(){
    self.showLocationRequestController(
                        setTitle: "We need your location for some awesome features",
                        setAllowButtonTitle: "Alright",
                        setNotNowButtonTitle: "Not now",
                        setMapViewAlphaValue: 0.9,
                        setBackgroundViewColor: UIColor.lightGrayColor(),
                        setDelegate: self)
}

```

Also don't forget to apply to the LocationRequestDelegate if you want to get notified about different states of the STLocationRequestController

**Comment by apm-lucas-zacharias** [comment]
I know thats working fine. Im talking about the VC thats calling showLocationRequest(). I can't close it after showing LocationRequest

**Comment by SvenTiigi** [comment]
Got it!

So it might be the best to give me a code sample of how you present your ViewController and the code inside the ViewController to fix that problem.
But it seems thats it is not combined with the STLocationRequestController cause it's presenting itself modally where it got called and so it's not changing anything from ViewController where you call the STLocationRequestController. The first thing I would check is if your ViewController is presented modally and it's NOT presented by a show or push segue.

**Comment by apm-lucas-zacharias** [comment]
I present the VC modally:
<img width="261" alt="screen shot 2016-06-04 at 17 17 30" src="https://cloud.githubusercontent.com/assets/8128416/15800412/8639f182-2a78-11e6-9938-dc958710bcbd.png">

and then call 
`self.showLocationRequestController(
                        setTitle: NSLocalizedString("REQUEST_LOCATION_TITLE", comment: "We need your location for some awesome features"),
                        setAllowButtonTitle: NSLocalizedString("ALRIGHT", comment: "alright"),
                        setNotNowButtonTitle: NSLocalizedString("NOT_NOW", comment: "not now"),
                        setMapViewAlphaValue: 0.9,
                        setBackgroundViewColor: UIColor.lightGrayColor(),
                        setDelegate: self)
`
 and then use 
`@IBAction func closeClicked(sender: AnyObject)
    {
        self.navigationController?.dismissViewControllerAnimated(true, completion: nil)
    }`

to close the VC.

It's working fine if I don't call `self.showLocationRequestController` and just call `locationManager.requestWhenInUseAuthorization()`

**Comment by SvenTiigi** [comment]
Do you have embedded your ViewController which will be presented modally as you written in a UINavigationController? If not please change your closeClicked function from

``` objective-c
@IBAction func closeClicked(sender: AnyObject) {
    self.navigationController?.dismissViewControllerAnimated(true, completion: nil) 
}
```

to

``` objective-c
@IBAction func closeClicked(sender: AnyObject) {
    self.dismissViewControllerAnimated(true, completion: nil) 
}
```

**Comment by apm-lucas-zacharias** [comment]
Yes I have

**Comment by SvenTiigi** [comment]
So I tried to reproduce your problem in a new Xcode project and there is no problem by presenting a viewcontroller modally and on that viewcontroller call self.showLocationRequestController() and dismiss it by a IBAction func with self.dismissViewControllerAnimated() with no UINavigationController and self.navigationController?.dismissViewControllerAnimated() with an UINavigationController.
![bildschirmfoto 2016-06-04 um 17 45 56](https://cloud.githubusercontent.com/assets/11733014/15800520/4e72994e-2a7c-11e6-970f-1bf3756d6e97.png)
![bildschirmfoto 2016-06-04 um 17 46 04](https://cloud.githubusercontent.com/assets/11733014/15800521/53cff08a-2a7c-11e6-9edc-c3673c9980e9.png)
![bildschirmfoto 2016-06-04 um 17 46 20](https://cloud.githubusercontent.com/assets/11733014/15800522/56f6e4b2-2a7c-11e6-8493-6cdd330bd7fe.png)

Also you might tried to debug it and also before calling self.navigationController?.dismissViewControllerAnimated() print out your navigationController to check if its not nil `print(self.navigationController)`

So to give further help please provide the code inside your ViewController to have look what might causes that problem.

**Comment by SvenTiigi** [comment]
@LucasZL is your request still a current problem or did you found a solution for your problem?
