### ISSUE TITLE
using pod with Swift 3.0 project

### ISSUE THREAD

**Issue by Hero93** [SvenTiigi/STLocationRequest#15]
Hi!
I'm trying to use this cool library in a Swift 3.0 project with pod.
The problem is that when I'm doing pod install "Font-Awesome", 1.5.3 is installed instead of the 1.6.1, so the project doesn't compile because the 1.5.3 code is not written in Swift 3.0

What should I do :) ?

Thanks

Luca.

**Comment by SvenTiigi** [comment]
Hi Luca,

I fixed that issue by publishing a new Version of STLocationRequest (Version `1.3.6`).

Please do a `pod update` on your project and everything should be fine 👌

**Comment by Hero93** [comment]
You're Awesome ! Thank you very much :)

**Comment by SvenTiigi** [comment]
No problem 👍
