### ISSUE TITLE
Allow for Custom Locations

### ISSUE THREAD

**Issue by DaveInTO** [SvenTiigi/STLocationRequest#16]
I'd be super if I could specify a custom location.
Currently I have to edit the code and add the new location + GPS info.
Then updates to the code remove that custom location.

**Comment by SvenTiigi** [comment]
Hey DaveInTO,

please do a `pod update` on your project to update `STLocationRequest` pod to Version `1.4.0`.
I think this should fix your issue. 👍 

## 1.4.0 Description

From now on you can add your own custom places to the STLocationRequestController

## Example
```swift
// Add place via latitude and longitude
locationRequestController.addPlace(latitude: 51.960665, longitude: 7.626135)

// Add place via CLLocationCoordinate2D
let myCoordinate = CLLocationCoordinate2DMake(51.960665, 7.626135)
locationRequestController.addPlace(coordinate: myCoordinate)
```

## Only show custom places
If you wish to show only your custom places just set the `placesFilter` to `.customPlaces`

```swift
// Only your custom places will be shown
locationRequestController.placesFilter = [.customPlaces]
```

## Satellite Flyover
Please keep in mind to check if your location is available in 3D-Flyover mode. To check just go to Apple Maps App and search your location and tap on the 3D-Button

## Your place is awesome?
If you found an awesome place that should be default implemented to the `STLocationRequestController` then just contribute it via a pull request. 👍

**Comment by DaveInTO** [comment]
Thanks - Perfect
