### ISSUE TITLE
not working on IOS 11

### ISSUE THREAD

**Issue by applesolutions** [SvenTiigi/STLocationRequest#19]
Hi there, 

It docent work after upgraded to iOS 11. 

The popup box with "Alright" is clickable but docent accecpt the selection. 

But if pressing " Not now " it goes away as it should.

**Comment by SvenTiigi** [comment]
Hey @applesolutions,

Are you running the example application or are you using STLocationRequest as a Pod Dependency in your project? If you are using STLocationRequest as a Pod Dependency and the Location permission dialog does not appear, please check your `Info.plist` file if you supplied the `NSLocationWhenInUseUsageDescription` or `NSLocationAlwaysUsageDescription` key.

You can find more information in the ReadMe under `Info.plist` https://github.com/SvenTiigi/STLocationRequest/blob/master/README.md

**Comment by SvenTiigi** [comment]
Hey @applesolutions,

is your problem still present?

**Comment by SvenTiigi** [comment]
inactive issue
