### ISSUE TITLE
Swift 4.2 Support?

### ISSUE THREAD

**Issue by qodeboy** [SvenTiigi/STLocationRequest#22]
The library, and underlying FlyoverKit does not compile with Swift 4.2 with a lot of deprecation issues. Is update to 4.2 is expectable anywhere soon?

**Comment by SvenTiigi** [comment]
Hey @qodeboy 

Swift 4.2 compatibility is currently under development and will be released in the near future👌

For more information head over to the `develop` branch: https://github.com/SvenTiigi/STLocationRequest/tree/develop

**Comment by SvenTiigi** [comment]
A new version of `STLocationRequest` has been published 🙌 which includes Swift 4.2 compatibility

Please update `STLocationRequest` to the latest version [3.3.0](https://github.com/SvenTiigi/STLocationRequest/releases/tag/3.3.0)

I hope this should fix your issue

**Comment by qodeboy** [comment]
Wow, that was damn quick! Thanks for your work, this works like a charm now.

P.S. Just one compilation warning though: ```Umbrella header for module 'STLocationRequest' does not include header 'STLocationRequest.h'```, but this seems not affect anything.
