### ISSUE TITLE
UITapGestureRecognizer doesn't work

### ISSUE THREAD

**Issue by bojanstef** [SvenTiigi/STLocationRequest#5]
I'm using the mapView as the background for my login screen. I added a UITapGestureRecognizer to `self.view` but it hardly works. The Selector just does: `self.view.endEditing(true)` yet it only works very rarely after tapping the screen multiple times.

My only assumption is that since the screen is rotating; tap gestures are not always recognized. I tried implementing all different types of gestures and overriding UIGestureRecognizerDelegate methods but nothing seems to work.

Any ideas?

**Comment by SvenTiigi** [comment]
When you call self.showLocationRequestController(...) a new UIViewController loaded from the UIViewController and presented modally above your current UIViewController. So if you add a UITapGestureRecognizer on your self.view the TapRecognizer will not be called on the modally presented STLocationRequest-ViewController. 

A possible workaround for your problem would be that you add a MapView on your ViewController and use the class inside STLocationRequest called "STRotatingCamera" and add it to your MKMapView by calling var rotatingCamer = STRotatingCamera(mapView: self.mapView). For a example you can take a look inside the STLocationRequestController.swift file.
Another possible solution to dismiss the keyboard in a login screen would be to use the UITextFieldDelegate Method textFieldShouldReturn, when the user tapped the return key on the keyboard. For further help, a code sample of your application would be great.
