### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by royhsu** [SvenTiigi/STLocationRequest#6]
I found memory usage increased every time when a new STLocationRequestController was created and dismissed.
It seems like you didn't invalidate the timer.

Solution:
[viewDidLoad]
// assign the timer to a local var timer: NSTimer?
`timer = NSTimer.scheduledTimerWithTimeInterval(15, target: self, selector: "changeRandomFlyOverCity", userInfo: nil, repeats: true)`

[viewDidDisappear]
// invalidate the timer and release it.
`timer?.invalidate()`
`timer = nil`

**Comment by SvenTiigi** [comment]
Thank you for your bug report :+1: 
I've updated the STLocationRequestController Swift file and added your solution.
