### ISSUE TITLE
Compilation errors in STLocationRequestController

### ISSUE THREAD

**Issue by alex-ntousias** [SvenTiigi/STLocationRequest#7]
Hi, 

First let me say that your library looks awesome!
I'm trying to use it in my project but I'm having some problems.

I modified my Podfile to include STLocationRequest:

```
platform :ios, '8.0'
use_frameworks!

target 'Squirlo' do
pod 'Google/SignIn'
pod 'GoogleMaps'
pod 'STLocationRequest'
end

target 'SquirloTests' do
end

target 'SquirloUITests' do
end
```

This is the output I'm getting when I'm running `pod install`: 

```
Updating local specs repositories

CocoaPods 1.0.0 is available.
To update use: `gem install cocoapods`
Until we reach version 1.0 the features of CocoaPods can and will change.
We strongly recommend that you use the latest version at all times.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing Font-Awesome-Swift (1.4.7)
Using Google (2.0.4)
Using GoogleAppUtilities (1.1.0)
Using GoogleAuthUtilities (2.0.0)
Using GoogleInterchangeUtilities (1.2.0)
Using GoogleMaps (1.13.0)
Using GoogleNetworkingUtilities (1.2.0)
Using GoogleSignIn (3.0.0)
Using GoogleSymbolUtilities (1.1.0)
Using GoogleUtilities (1.3.0)
Installing STLocationRequest (0.2.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 11 total pods installed.
```

The problem is that when I go back to Xcode, I'm getting compilation errors coming from `STLocationRequestController`. In particular the compilation error I'm getting is for the following line:

```
self.timer = NSTimer.scheduledTimerWithTimeInterval(15, target: self, selector: #selector(STLocationRequestController.changeRandomFlyOverCity), userInfo: nil, repeats: true)
```

I can fix that by manually changing the above line to the following:

```
self.timer = NSTimer.scheduledTimerWithTimeInterval(15, target: self, selector: "changeRandomFlyOverCity", userInfo: nil, repeats: true)
```

After fixing the above error, I'm trying to use the library but when I'm trying to `import STLocationRequest` I'm getting an error saying `No such module 'STLocationRequest'`

What am I doing wrong?

Many thanks, 
Alex

**Comment by SvenTiigi** [comment]
Hey Alex,

thank you for using STLocationRequest in your iOS Project 👍 

It seems like that your Xcode Version and your Swift Version is not up to date.

STLocationRequest is written in Swift 2.2 and so a string literal selector (selector: "changeRandomFlyOverCity") is deprecated. 
For more information check out this link:
http://stackoverflow.com/a/24007718

So to fix this issue just update your Xcode Version by going to the Mac App Store.
If Xcode says `No such module...` just build your project by hitting `cmd+b` Xcode will reindex the pods and the error should be gone.
