### ISSUE TITLE
The flyover part of is not working?

### ISSUE THREAD

**Issue by JeanPierreFig** [SvenTiigi/STLocationRequest#8]
I just download it and installed the pod but it just shows up like this 
![simulator screen shot may 16 2016 1 12 54 pm](https://cloud.githubusercontent.com/assets/13212319/15297405/ed82dca2-1b67-11e6-8714-3c6ff5696487.png)

**Comment by SvenTiigi** [comment]
Hey JeanPierreFig,

just have a look at the ReadMe File (https://github.com/SvenTiigi/STLocationRequest/blob/master/README.md)

## Simulator

Please mind that the 3D Flyover-View will only work on a real iOS device (not in the Simulator) with at least iOS 9.0 installed. A 2D fallback for Simulator or iOS 8.0 devices is already integrated.
